# battery:
#   energy_capacity_mwh: 100.0
#   power_capacity_mw: 50.0
#   charge_efficiency: 0.95
#   discharge_efficiency: 0.95
#   min_soc: 0.10
#   max_soc: 0.90
#   degradation_cost_per_mwh: 2.0

# battery_file: examples/batteries/1_moss_landing.yaml
battery_file: examples/batteries/0_flagstaff_theoretical.yaml

strategy:
  name: schedule
  params:
    # Charge during [charge_start, charge_end) each day.
    charge_start: "11:00"
    charge_end: "15:00"
    charge_power_mw: 100.0

    # Discharge during [discharge_start, discharge_end) each day.
    discharge_start: "16:00"
    discharge_end: "23:59"
    discharge_power_mw: 100.0

